### ISSUE TITLE
Feature Request: ability to put comments in Procfiles

### ISSUE THREAD

**Issue by ruckus** [ddollar/foreman#12]
I'd like to add comments to my Procfile, I tried starting a line with "#" but it complained and failed to boot.

Comments would be great for documentation for team projects.

**Comment by Matt--** [comment]
+1 for comments

**Comment by ericraio** [comment]
+1 for comments

**Comment by beornborn** [comment]
+1 for comments

**Comment by marksterxxx** [comment]
+1 for comments

**Comment by adisos** [comment]
+1 for comments

**Comment by reconstructions** [comment]
+1 for comments

**Comment by diziet** [comment]
+1, especially as we want to have a Profile.example that folks can use easily

**Comment by ddollar** [comment]
Foreman has used a matching filter on the Procfile to only parse lines that look like process entries for a few years now. Are you still running into problems with thos?

**Comment by diziet** [comment]
@ddollar  You're correct -- appending # to the beginning of line at the Procfile effectively makes it function like a comment. Sorry for bringing up a nonexistent issue.

**Comment by billywatson** [comment]
I swear I tried it at some point and it didn't work, but it's totally working now. Thanks, guys.

**Comment by jwfearn** [comment]
Using foreman 0.82.0 on OS X 10.11.5 and Ruby 2.1.2 I found that lines starting with `#` **ARE** processed, whereas lines starting with `//` are ignored.  For example this `Procfile`:

```
# foo: cd foo && bundle exec rails s -p 3000
// bar: cd bar && bundle exec rails s -p 3001
baz: cd baz && bundle exec rails s -p 3002
```

starts two processes: `foo` and `baz`

Would it be possible to add true comments rather than a parser-matching-filter to recognize lines that look like process entries?

If so, please also update docs to indicate how comments work (e.g., comment string: #, //, or other?, whole lines only?, end of line only?, multi-line? __END__? etc.)

**Comment by mitchellporter** [comment]
+1 for comments

**Comment by benzittlau** [comment]
+1 for comments

**Comment by RawStewage** [comment]
+1 for comments

**Comment by Erowlin** [comment]
Bump.

**Comment by jpwynn** [comment]
It's a file.

+1 for DOCUMENTING the format for a comment...

**Comment by OdyAsh** [comment]
+1 for comments
