### ISSUE TITLE
Would be useful to provide a "foreman stop" command

### ISSUE THREAD

**Issue by rtyler** [ddollar/foreman#156]
In the case where you're in another terminal, or have backgrounded the foreman process with `&` (which I plan to do inside of a Jenkins job), it would be useful to have a `foreman stop` stop the process the same way that a `Ctrl+C` might work

**Comment by waxgenius** [comment]
Why was this closed?

**Comment by ddollar** [comment]
Foreman is designed to be run in the foreground. This feature would add a lot of complexity (how do we know which foreman to stop) for something outside the primary use case.

**Comment by sebs** [comment]
I know it is a old one, but I have to clear some state after ^C occurs. Hence I googled this ticket. he state is a PID file that I need to get out of the way.

**Comment by axelkennedal** [comment]
Having the exact same problem as @sebs and would really like a fix for this. I'm using Foreman for the dev environment for a React + Electron desktop app (per the recommendation of [this](https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c) article) where I start a dev server at localhost:5000. When I hit ctrl-C Foreman quits, but it leaves the server running and still listening at :5000, meaning that when I attempt to start my Foreman service again it throws an error because there is already another process listening to :5000.

**Comment by sebs** [comment]
My Scenario: I start a docker environment with 

```shell
forman start
.... executes docker-compose up --build 
``` 
I 

I use STG+C and in one of 1000 cases, the docker magic fails. Let it be a filehandle open blocking a shutdown of your app or a db connection.

So I would love to have a stupid list of forman stop to clean all the state that I want to clean. Just in case. In my case, this would be a 

```
docker-compose down
```
