### ISSUE TITLE
Foreman fails to install on debian jessie (testing)

### ISSUE THREAD

**Issue by djcp** [ddollar/foreman#458]
foreman fails to install on debian jessie because it relies on the metapackage `ruby1.9.1` which [has been removed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739611) by the debian ruby maintainers. This will eventually propagate to most debian derivatives, presumably.

A fix would be to depend on a more modern ruby (ruby2.1?), assuming foreman works OK under that vendor distributed ruby version (it probably does).

Should I take a stab at fixing this dependency?

**Comment by stumyp** [comment]
I'm not sure if I should open new issue or re-open this one:
But current version of The Foreman can not be installed on recent version of Debian/Jessie due to overlapping files:

```dpkg: error processing archive /var/cache/apt/archives/ruby-rdoc_3.12.2-1_all.deb (--unpack):
 trying to overwrite '/usr/bin/rdoc', which is also in package ruby 1:2.1.5```

`ruby-rdoc` depends on `ruby` and conflicts with it ...

I don't see how can I resolve this issue on system level. Rebuilding the deb files without rdoc dependency might help.

**Comment by bluehorseshoe1** [comment]
Seeing the same thing.

dpkg: error processing archive /var/cache/apt/archives/ruby-rdoc_3.12.2-1_all.deb (--unpack):

**Comment by rmchale** [comment]
I am seeing this issue

**Comment by spengilley** [comment]
This issue should be open or linked to a fix. Trying to install the foreman and getting the same error as reported by stumyp
