### ISSUE TITLE
Not parsing the Procfile as YAML breaks multiline command syntax

### ISSUE THREAD

**Issue by benwilber** [ddollar/foreman#532]
* Source: https://github.com/ddollar/foreman/blob/master/lib/foreman/procfile.rb#L86

I'm confused why this would be parsed manually instead of just loading it as a YAML file?  That implementation breaks on "folded" YAML syntax like so:

```
web: >
    command --option1 --option3 --option4 --option5
    --option6 --option7 --option8 --option9
```

**Comment by ddollar** [comment]
Procfiles are not in YAML format, they are in the format:

```
name1: command
name2: command
```

**Comment by perlun** [comment]
@ddollar An old issue, but is this something that you consider changing if someone would submit a PR? I also ran into the same issue right now: assumed that the file was YAML (since it "looks like YAML" at first glance) and tried to use multi-line syntax for a more complex command, which didn't work.

What is the main reason for not parsing it as YAML?
