### ISSUE TITLE
0.19.3 did not resolve this issue: "run" is a Thor reserved word and cannot be defined as command (RuntimeError)

### ISSUE THREAD

**Issue by ThomasConnolly** [ddollar/foreman#655]

**Comment by irobayna** [comment]
same issue
```ruby
foreman start
/ruby-2.3.3/gems/thor-0.19.3/lib/thor/base.rb:534:in `thor_reserved_word?': "run" is a Thor reserved word and cannot be defined as command (RuntimeError)
	from /ruby-2.3.3/gems/thor-0.19.3/lib/thor/base.rb:597:in `method_added'
	from /ruby-2.3.3/gems/foreman-0.82.0/lib/foreman/cli.rb:80:in `<class:CLI>'
	from /ruby-2.3.3/gems/foreman-0.82.0/lib/foreman/cli.rb:11:in `<top (required)>'
	from /ruby-2.3.3/gems/foreman-0.82.0/bin/foreman:5:in `require'
	from /ruby-2.3.3/gems/foreman-0.82.0/bin/foreman:5:in `<top (required)>'
	from /ruby-2.3.3/bin/foreman:22:in `load'
	from /ruby-2.3.3/bin/foreman:22:in `<main>'
	from /ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dpandoffx** [comment]
+1

**Comment by juno** [comment]
Root cause is that thor 0.19.2 changed it's protected method name in [this](https://github.com/erikhuda/thor/commit/3e2dfe9d431758b2aa0996e304744881dc78825c#diff-ffcb86f580effa19deae13c3f3ec990f) commit.
- Before:
  - `Thor::Base.is_thor_reserved_word?`
- After:
  - `Thor::Base.thor_reserved_word?`

foreman has override that method in [cli.rb](https://github.com/ddollar/foreman/blob/5f5502efed74c68f5cf381d38b2ad497676837ec/lib/foreman/cli.rb#L30
), and it's not compatible to thor 0.19.2.

```ruby
    # Hackery. Take the run method away from Thor so that we can redefine it.
    def is_thor_reserved_word?(word, type)
      return false if word == "run"
      super
    end
```

**Comment by sferik** [comment]
I did not intend to make a breaking change by renaming `is_thor_reserved_word?`.

I will change it back and release 0.19.4.

**Comment by kenaniah** [comment]
This is resolved in https://github.com/erikhuda/thor/commit/329cff6692c040fec7dfb67cc1fa742d31d5b97d and the `0.19.4` release. Please close this issue.

**Comment by ThomasConnolly** [comment]
Thanks!
